### PR TITLE
add ConnectionWaadOptions

### PR DESCRIPTION
**Pull request by fabriziomoscon**
Hi there,
I have added some more options for waad connection as required by my use case.

I'd love to hear from @alexkappa what he thinks?

### CODE REVIEW

**Comment by alexkappa** [comment]
Hi @fabriziomoscon, thank you for contributing! Could you please point me to some documentation about this options? I cannot find something related in the [management docs](https://auth0.com/docs/api/management/v2#!/Connections/get_connections_by_id).

**Comment by fabriziomoscon** [comment]
Hi, I reverse engineered Auth0 result of the API endpoint /api/v2/connections as I didn't find docs.
this https://github.com/yieldr/terraform-provider-auth0/pull/12 has a test to see it working

**Comment by alexkappa** [comment]
I was able to verify these fields after creating an Azure Microsoft Azure AD connection, but I am reluctant to merge this as it might be an undocumented feature which Auth0 might decide to break at any moment. Perhaps we should engage with Auth0 to get more info on this? 

I also can't find references in Auth0 official SDKs (checked Java and PHP). They use generic types for options all together.

**Comment by alexkappa** [comment]
As the change is not so disruptive, lets merge it and if something changes from Auth0 we can deal with it then. Thanks @fabriziomoscon!

**Comment by fabriziomoscon** [comment]
@alexkappa please consider releasing a new tag for this merge, as it would simplify `dep` usage

**Comment by alexkappa** [comment]
@fabriziomoscon sure thing, I've cut [v.0.0.8](https://github.com/yieldr/go-auth0/releases/tag/v0.0.8) based on the latest master.

**Pull request merged**
