### PR TITLE
Add `ShowAsButton` option

### PR DESCRIPTION
**Pull request by mdreizin**
### Proposed Changes

* Add a new `show_as_button` option to be able to show a connection as a button (related to https://github.com/alexkappa/terraform-provider-auth0/issues/493)

#### Acceptance Test Output

```
$ go test ./... -v -run TestUser
```

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

### CODE REVIEW

**Comment by mdreizin** [comment]
@alexkappa could you please review it? :)

PS: Auth0 ticket #00511292 about adding missing documentation is submitted. I hope, Auth0 team will update the documentation soon.

**Comment by willvedd** [comment]
>PS: Auth0 ticket #00511292 about adding missing documentation is submitted. I hope, Auth0 team will update the documentation soon.

@mdreizin do you mind elaborating on the missing documentation?

**Comment by mdreizin** [comment]
@willvedd as far I may understand Auth0 team is working on that right now. If Auth0 documentation is open then I will be happy to help.

**Comment by mdreizin** [comment]
Do you have any updates on this?

**Comment by sergiught** [comment]
Hi @mdreizin, thanks for your contribution. This project is now being maintained at https://github.com/auth0/go-auth0 and unfortunately we are unable to transfer open PRs. Would you mind resubmitting this against that repository? 🙏🏻

**Pull request closed without merging**
